// Mocks generated by Mockito 5.4.6 from annotations
// in tesla_android/test/unit/cubits/audio_configuration_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tesla_android/feature/settings/model/system_configuration_response_body.dart'
    as _i2;
import 'package:tesla_android/feature/settings/repository/system_configuration_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSystemConfigurationResponseBody_0 extends _i1.SmartFake
    implements _i2.SystemConfigurationResponseBody {
  _FakeSystemConfigurationResponseBody_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [SystemConfigurationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemConfigurationRepository extends _i1.Mock
    implements _i3.SystemConfigurationRepository {
  MockSystemConfigurationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SystemConfigurationResponseBody> getConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#getConfiguration, []),
            returnValue: _i4.Future<_i2.SystemConfigurationResponseBody>.value(
              _FakeSystemConfigurationResponseBody_0(
                this,
                Invocation.method(#getConfiguration, []),
              ),
            ),
          )
          as _i4.Future<_i2.SystemConfigurationResponseBody>);

  @override
  _i4.Future<dynamic> setSoftApBand(int? band) =>
      (super.noSuchMethod(
            Invocation.method(#setSoftApBand, [band]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setSoftApChannel(int? channel) =>
      (super.noSuchMethod(
            Invocation.method(#setSoftApChannel, [channel]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setSoftApChannelWidth(int? channelWidth) =>
      (super.noSuchMethod(
            Invocation.method(#setSoftApChannelWidth, [channelWidth]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setSoftApState(int? isEnabledFlag) =>
      (super.noSuchMethod(
            Invocation.method(#setSoftApState, [isEnabledFlag]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setOfflineModeState(int? isEnabledFlag) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineModeState, [isEnabledFlag]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setOfflineModeTelemetryState(int? isEnabledFlag) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineModeTelemetryState, [isEnabledFlag]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setOfflineModeTeslaFirmwareDownloads(
    int? isEnabledFlag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setOfflineModeTeslaFirmwareDownloads, [
              isEnabledFlag,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setBrowserAudioState(int? isEnabledFlag) =>
      (super.noSuchMethod(
            Invocation.method(#setBrowserAudioState, [isEnabledFlag]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setBrowserAudioVolume(int? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setBrowserAudioVolume, [volume]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> setGPSState(int? isEnabled) =>
      (super.noSuchMethod(
            Invocation.method(#setGPSState, [isEnabled]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
