// Mocks generated by Mockito 5.4.6 from annotations
// in tesla_android/test/unit/cubits/display_configuration_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tesla_android/feature/display/model/remote_display_state.dart'
    as _i2;
import 'package:tesla_android/feature/display/repository/display_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRemoteDisplayState_0 extends _i1.SmartFake
    implements _i2.RemoteDisplayState {
  _FakeRemoteDisplayState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DisplayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisplayRepository extends _i1.Mock implements _i3.DisplayRepository {
  MockDisplayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RemoteDisplayState> getDisplayState() =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayState, []),
            returnValue: _i4.Future<_i2.RemoteDisplayState>.value(
              _FakeRemoteDisplayState_0(
                this,
                Invocation.method(#getDisplayState, []),
              ),
            ),
          )
          as _i4.Future<_i2.RemoteDisplayState>);

  @override
  _i4.Future<dynamic> updateDisplayConfiguration(
    _i2.RemoteDisplayState? configuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayConfiguration, [configuration]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<bool?> isPrimaryDisplay() =>
      (super.noSuchMethod(
            Invocation.method(#isPrimaryDisplay, []),
            returnValue: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<dynamic> setDisplayType(bool? isPrimaryDisplay) =>
      (super.noSuchMethod(
            Invocation.method(#setDisplayType, [isPrimaryDisplay]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
