// Mocks generated by Mockito 5.4.6 from annotations
// in tesla_android/test/helpers/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i9;

import 'package:dio/dio.dart' as _i6;
import 'package:flavor/flavor.dart' as _i17;
import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:tesla_android/common/navigation/ta_page.dart' as _i16;
import 'package:tesla_android/common/navigation/ta_page_factory.dart' as _i15;
import 'package:tesla_android/common/network/device_info_service.dart' as _i14;
import 'package:tesla_android/common/network/github_service.dart' as _i12;
import 'package:tesla_android/common/service/audio_service.dart' as _i7;
import 'package:tesla_android/common/service/dialog_service.dart' as _i18;
import 'package:tesla_android/common/service/window_service.dart' as _i10;
import 'package:tesla_android/feature/home/model/github_release.dart' as _i2;
import 'package:tesla_android/feature/settings/model/device_info.dart' as _i3;
import 'package:tesla_android/feature/touchscreen/service/message_sender.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGitHubRelease_0 extends _i1.SmartFake implements _i2.GitHubRelease {
  _FakeGitHubRelease_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceInfo_1 extends _i1.SmartFake implements _i3.DeviceInfo {
  _FakeDeviceInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeBaseOptions_3 extends _i1.SmartFake implements _i6.BaseOptions {
  _FakeBaseOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_4 extends _i1.SmartFake
    implements _i6.HttpClientAdapter {
  _FakeHttpClientAdapter_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_5 extends _i1.SmartFake implements _i6.Transformer {
  _FakeTransformer_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_6 extends _i1.SmartFake implements _i6.Interceptors {
  _FakeInterceptors_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_7<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_8 extends _i1.SmartFake implements _i6.Dio {
  _FakeDio_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i7.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setupAudioConfig(String? configJson) => super.noSuchMethod(
    Invocation.method(#setupAudioConfig, [configJson]),
    returnValueForMissingStub: null,
  );

  @override
  void startAudioFromGesture() => super.noSuchMethod(
    Invocation.method(#startAudioFromGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAudio() => super.noSuchMethod(
    Invocation.method(#stopAudio, []),
    returnValueForMissingStub: null,
  );

  @override
  String getAudioState() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioState, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAudioState, []),
            ),
          )
          as String);

  @override
  _i9.VoidCallback addAudioStateListener(void Function(String)? onState) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioStateListener, [onState]),
            returnValue: () {},
          )
          as _i9.VoidCallback);
}

/// A class which mocks [WindowService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowService extends _i1.Mock implements _i10.WindowService {
  MockWindowService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void reload() => super.noSuchMethod(
    Invocation.method(#reload, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MessageSender].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageSender extends _i1.Mock implements _i11.MessageSender {
  MockMessageSender() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void postMessage(String? message, String? targetOrigin) => super.noSuchMethod(
    Invocation.method(#postMessage, [message, targetOrigin]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GitHubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubService extends _i1.Mock implements _i12.GitHubService {
  MockGitHubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.GitHubRelease> getLatestRelease() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestRelease, []),
            returnValue: _i13.Future<_i2.GitHubRelease>.value(
              _FakeGitHubRelease_0(
                this,
                Invocation.method(#getLatestRelease, []),
              ),
            ),
          )
          as _i13.Future<_i2.GitHubRelease>);
}

/// A class which mocks [DeviceInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoService extends _i1.Mock implements _i14.DeviceInfoService {
  MockDeviceInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.DeviceInfo> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i13.Future<_i3.DeviceInfo>.value(
              _FakeDeviceInfo_1(this, Invocation.method(#getDeviceInfo, [])),
            ),
          )
          as _i13.Future<_i3.DeviceInfo>);

  @override
  _i13.Future<dynamic> openUpdater() =>
      (super.noSuchMethod(
            Invocation.method(#openUpdater, []),
            returnValue: _i13.Future<dynamic>.value(),
          )
          as _i13.Future<dynamic>);
}

/// A class which mocks [TAPageFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockTAPageFactory extends _i1.Mock implements _i15.TAPageFactory {
  MockTAPageFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get initialRoute =>
      (super.noSuchMethod(
            Invocation.getter(#initialRoute),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#initialRoute),
            ),
          )
          as String);

  @override
  set initialRoute(String? _initialRoute) => super.noSuchMethod(
    Invocation.setter(#initialRoute, _initialRoute),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, _i4.Widget Function(_i4.BuildContext)> getRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#getRoutes, []),
            returnValue: <String, _i4.Widget Function(_i4.BuildContext)>{},
          )
          as Map<String, _i4.Widget Function(_i4.BuildContext)>);

  @override
  _i4.Widget Function(_i4.BuildContext) buildPage(_i16.TAPage? page) =>
      (super.noSuchMethod(
            Invocation.method(#buildPage, [page]),
            returnValue: (_i4.BuildContext context) =>
                _FakeWidget_2(this, Invocation.method(#buildPage, [page])),
          )
          as _i4.Widget Function(_i4.BuildContext));
}

/// A class which mocks [Flavor].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavor extends _i1.Mock implements _i17.Flavor {
  MockFlavor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.Environment get environment =>
      (super.noSuchMethod(
            Invocation.getter(#environment),
            returnValue: _i17.Environment.dev,
          )
          as _i17.Environment);

  @override
  bool get isDevelopment =>
      (super.noSuchMethod(Invocation.getter(#isDevelopment), returnValue: false)
          as bool);

  @override
  bool get isAlpha =>
      (super.noSuchMethod(Invocation.getter(#isAlpha), returnValue: false)
          as bool);

  @override
  bool get isBeta =>
      (super.noSuchMethod(Invocation.getter(#isBeta), returnValue: false)
          as bool);

  @override
  bool get isProduction =>
      (super.noSuchMethod(Invocation.getter(#isProduction), returnValue: false)
          as bool);

  @override
  Object? getObject(String? key) =>
      (super.noSuchMethod(Invocation.method(#getObject, [key])) as Object?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i6.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_3(this, Invocation.getter(#options)),
          )
          as _i6.BaseOptions);

  @override
  _i6.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_4(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i6.HttpClientAdapter);

  @override
  _i6.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_5(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i6.Transformer);

  @override
  _i6.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_6(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i6.Interceptors);

  @override
  set options(_i6.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i6.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i6.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i6.Options? options,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i6.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i6.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i6.FileAccessMode? fileAccessMode = _i6.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i6.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i6.ProgressCallback? onReceiveProgress,
    _i6.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i6.FileAccessMode? fileAccessMode = _i6.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i6.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i6.CancelToken? cancelToken,
    _i6.Options? options,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i6.CancelToken? cancelToken,
    _i6.Options? options,
    _i6.ProgressCallback? onSendProgress,
    _i6.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> fetch<T>(_i6.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i6.Dio clone({
    _i6.BaseOptions? options,
    _i6.Interceptors? interceptors,
    _i6.HttpClientAdapter? httpClientAdapter,
    _i6.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_8(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i6.Dio);
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i18.DialogService {
  MockDialogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void showMaterialBanner({
    required _i4.BuildContext? context,
    required _i4.MaterialBanner? banner,
  }) => super.noSuchMethod(
    Invocation.method(#showMaterialBanner, [], {
      #context: context,
      #banner: banner,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clearMaterialBanners({required _i4.BuildContext? context}) =>
      super.noSuchMethod(
        Invocation.method(#clearMaterialBanners, [], {#context: context}),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<T?> showDialog<T>({
    required _i4.BuildContext? context,
    required _i4.WidgetBuilder? builder,
    bool? barrierDismissible = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showDialog, [], {
              #context: context,
              #builder: builder,
              #barrierDismissible: barrierDismissible,
            }),
            returnValue: _i13.Future<T?>.value(),
          )
          as _i13.Future<T?>);
}
