// Mocks generated by Mockito 5.4.6 from annotations
// in tesla_android/test/helpers/mock_cubits.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i24;

import 'package:flutter/cupertino.dart' as _i28;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i31;
import 'package:tesla_android/common/service/audio_service.dart' as _i30;
import 'package:tesla_android/feature/connectivityCheck/cubit/connectivity_check_cubit.dart'
    as _i21;
import 'package:tesla_android/feature/connectivityCheck/model/connectivity_state.dart'
    as _i22;
import 'package:tesla_android/feature/display/cubit/display_cubit.dart' as _i23;
import 'package:tesla_android/feature/display/cubit/display_state.dart' as _i8;
import 'package:tesla_android/feature/display/model/remote_display_state.dart'
    as _i17;
import 'package:tesla_android/feature/home/cubit/ota_update_cubit.dart' as _i25;
import 'package:tesla_android/feature/home/cubit/ota_update_state.dart' as _i9;
import 'package:tesla_android/feature/releaseNotes/cubit/release_notes_cubit.dart'
    as _i32;
import 'package:tesla_android/feature/releaseNotes/cubit/release_notes_state.dart'
    as _i10;
import 'package:tesla_android/feature/releaseNotes/model/changelog_item.dart'
    as _i34;
import 'package:tesla_android/feature/releaseNotes/model/version.dart' as _i33;
import 'package:tesla_android/feature/settings/bloc/audio_configuration_cubit.dart'
    as _i15;
import 'package:tesla_android/feature/settings/bloc/audio_configuration_state.dart'
    as _i3;
import 'package:tesla_android/feature/settings/bloc/device_info_cubit.dart'
    as _i20;
import 'package:tesla_android/feature/settings/bloc/device_info_state.dart'
    as _i7;
import 'package:tesla_android/feature/settings/bloc/display_configuration_cubit.dart'
    as _i16;
import 'package:tesla_android/feature/settings/bloc/display_configuration_state.dart'
    as _i4;
import 'package:tesla_android/feature/settings/bloc/gps_configuration_cubit.dart'
    as _i19;
import 'package:tesla_android/feature/settings/bloc/gps_configuration_state.dart'
    as _i6;
import 'package:tesla_android/feature/settings/bloc/rear_display_configuration_cubit.dart'
    as _i18;
import 'package:tesla_android/feature/settings/bloc/rear_display_configuration_state.dart'
    as _i5;
import 'package:tesla_android/feature/settings/bloc/system_configuration_cubit.dart'
    as _i11;
import 'package:tesla_android/feature/settings/bloc/system_configuration_state.dart'
    as _i2;
import 'package:tesla_android/feature/settings/model/softap_band_type.dart'
    as _i13;
import 'package:tesla_android/feature/touchscreen/cubit/touchscreen_cubit.dart'
    as _i26;
import 'package:tesla_android/feature/touchscreen/model/virtual_touchscreen_command.dart'
    as _i29;
import 'package:tesla_android/feature/touchscreen/model/virtual_touchscreen_slot_state.dart'
    as _i27;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSystemConfigurationState_0 extends _i1.SmartFake
    implements _i2.SystemConfigurationState {
  _FakeSystemConfigurationState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioConfigurationState_1 extends _i1.SmartFake
    implements _i3.AudioConfigurationState {
  _FakeAudioConfigurationState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDisplayConfigurationState_2 extends _i1.SmartFake
    implements _i4.DisplayConfigurationState {
  _FakeDisplayConfigurationState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRearDisplayConfigurationState_3 extends _i1.SmartFake
    implements _i5.RearDisplayConfigurationState {
  _FakeRearDisplayConfigurationState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGPSConfigurationState_4 extends _i1.SmartFake
    implements _i6.GPSConfigurationState {
  _FakeGPSConfigurationState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeviceInfoState_5 extends _i1.SmartFake
    implements _i7.DeviceInfoState {
  _FakeDeviceInfoState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDisplayState_6 extends _i1.SmartFake implements _i8.DisplayState {
  _FakeDisplayState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOTAUpdateState_7 extends _i1.SmartFake
    implements _i9.OTAUpdateState {
  _FakeOTAUpdateState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReleaseNotesState_8 extends _i1.SmartFake
    implements _i10.ReleaseNotesState {
  _FakeReleaseNotesState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SystemConfigurationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemConfigurationCubit extends _i1.Mock
    implements _i11.SystemConfigurationCubit {
  MockSystemConfigurationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SystemConfigurationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSystemConfigurationState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.SystemConfigurationState);

  @override
  _i12.Stream<_i2.SystemConfigurationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i2.SystemConfigurationState>.empty(),
          )
          as _i12.Stream<_i2.SystemConfigurationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConfiguration, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void updateSoftApBand(_i13.SoftApBandType? newBand) => super.noSuchMethod(
    Invocation.method(#updateSoftApBand, [newBand]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSoftApState(bool? isEnabled) => super.noSuchMethod(
    Invocation.method(#updateSoftApState, [isEnabled]),
    returnValueForMissingStub: null,
  );

  @override
  void updateOfflineModeState(bool? isEnabled) => super.noSuchMethod(
    Invocation.method(#updateOfflineModeState, [isEnabled]),
    returnValueForMissingStub: null,
  );

  @override
  void updateOfflineModeTelemetryState(bool? isEnabled) => super.noSuchMethod(
    Invocation.method(#updateOfflineModeTelemetryState, [isEnabled]),
    returnValueForMissingStub: null,
  );

  @override
  void updateOfflineModeTeslaFirmwareDownloadsState(bool? isEnabled) =>
      super.noSuchMethod(
        Invocation.method(#updateOfflineModeTeslaFirmwareDownloadsState, [
          isEnabled,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void applySystemConfiguration() => super.noSuchMethod(
    Invocation.method(#applySystemConfiguration, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.SystemConfigurationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i2.SystemConfigurationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioConfigurationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioConfigurationCubit extends _i1.Mock
    implements _i15.AudioConfigurationCubit {
  MockAudioConfigurationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioConfigurationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAudioConfigurationState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.AudioConfigurationState);

  @override
  _i12.Stream<_i3.AudioConfigurationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i3.AudioConfigurationState>.empty(),
          )
          as _i12.Stream<_i3.AudioConfigurationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<dynamic> fetchConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConfiguration, []),
            returnValue: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  void setVolume(int? newVolume) => super.noSuchMethod(
    Invocation.method(#setVolume, [newVolume]),
    returnValueForMissingStub: null,
  );

  @override
  void setState(bool? isEnabled) => super.noSuchMethod(
    Invocation.method(#setState, [isEnabled]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.AudioConfigurationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i3.AudioConfigurationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DisplayConfigurationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisplayConfigurationCubit extends _i1.Mock
    implements _i16.DisplayConfigurationCubit {
  MockDisplayConfigurationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DisplayConfigurationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDisplayConfigurationState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.DisplayConfigurationState);

  @override
  _i12.Stream<_i4.DisplayConfigurationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i4.DisplayConfigurationState>.empty(),
          )
          as _i12.Stream<_i4.DisplayConfigurationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void fetchConfiguration() => super.noSuchMethod(
    Invocation.method(#fetchConfiguration, []),
    returnValueForMissingStub: null,
  );

  @override
  void setResponsiveness(bool? newSetting) => super.noSuchMethod(
    Invocation.method(#setResponsiveness, [newSetting]),
    returnValueForMissingStub: null,
  );

  @override
  void setResolution(_i17.DisplayResolutionModePreset? newPreset) =>
      super.noSuchMethod(
        Invocation.method(#setResolution, [newPreset]),
        returnValueForMissingStub: null,
      );

  @override
  void setRenderer(_i17.DisplayRendererType? newType) => super.noSuchMethod(
    Invocation.method(#setRenderer, [newType]),
    returnValueForMissingStub: null,
  );

  @override
  void setQuality(_i17.DisplayQualityPreset? newQuality) => super.noSuchMethod(
    Invocation.method(#setQuality, [newQuality]),
    returnValueForMissingStub: null,
  );

  @override
  void setRefreshRate(_i17.DisplayRefreshRatePreset? newRefreshRate) =>
      super.noSuchMethod(
        Invocation.method(#setRefreshRate, [newRefreshRate]),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.DisplayConfigurationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i4.DisplayConfigurationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RearDisplayConfigurationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockRearDisplayConfigurationCubit extends _i1.Mock
    implements _i18.RearDisplayConfigurationCubit {
  MockRearDisplayConfigurationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.RearDisplayConfigurationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeRearDisplayConfigurationState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.RearDisplayConfigurationState);

  @override
  _i12.Stream<_i5.RearDisplayConfigurationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i5.RearDisplayConfigurationState>.empty(),
          )
          as _i12.Stream<_i5.RearDisplayConfigurationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void fetchConfiguration() => super.noSuchMethod(
    Invocation.method(#fetchConfiguration, []),
    returnValueForMissingStub: null,
  );

  @override
  void setRearDisplayState(bool? newSetting) => super.noSuchMethod(
    Invocation.method(#setRearDisplayState, [newSetting]),
    returnValueForMissingStub: null,
  );

  @override
  void setRearDisplayPrioritization(bool? newSetting) => super.noSuchMethod(
    Invocation.method(#setRearDisplayPrioritization, [newSetting]),
    returnValueForMissingStub: null,
  );

  @override
  void setDisplayType({required bool? isCurrentDisplayPrimary}) =>
      super.noSuchMethod(
        Invocation.method(#setDisplayType, [], {
          #isCurrentDisplayPrimary: isCurrentDisplayPrimary,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.RearDisplayConfigurationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i5.RearDisplayConfigurationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GPSConfigurationCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockGPSConfigurationCubit extends _i1.Mock
    implements _i19.GPSConfigurationCubit {
  MockGPSConfigurationCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GPSConfigurationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeGPSConfigurationState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.GPSConfigurationState);

  @override
  _i12.Stream<_i6.GPSConfigurationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i6.GPSConfigurationState>.empty(),
          )
          as _i12.Stream<_i6.GPSConfigurationState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<dynamic> fetchConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#fetchConfiguration, []),
            returnValue: _i12.Future<dynamic>.value(),
          )
          as _i12.Future<dynamic>);

  @override
  void setState(bool? newState) => super.noSuchMethod(
    Invocation.method(#setState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.GPSConfigurationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i6.GPSConfigurationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DeviceInfoCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoCubit extends _i1.Mock implements _i20.DeviceInfoCubit {
  MockDeviceInfoCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.DeviceInfoState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDeviceInfoState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.DeviceInfoState);

  @override
  _i12.Stream<_i7.DeviceInfoState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i7.DeviceInfoState>.empty(),
          )
          as _i12.Stream<_i7.DeviceInfoState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void fetchConfiguration() => super.noSuchMethod(
    Invocation.method(#fetchConfiguration, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.DeviceInfoState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i7.DeviceInfoState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ConnectivityCheckCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityCheckCubit extends _i1.Mock
    implements _i21.ConnectivityCheckCubit {
  MockConnectivityCheckCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onReloadOverride(void Function()? _onReloadOverride) =>
      super.noSuchMethod(
        Invocation.setter(#onReloadOverride, _onReloadOverride),
        returnValueForMissingStub: null,
      );

  @override
  _i22.ConnectivityState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i22.ConnectivityState.backendAccessible,
          )
          as _i22.ConnectivityState);

  @override
  _i12.Stream<_i22.ConnectivityState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i22.ConnectivityState>.empty(),
          )
          as _i12.Stream<_i22.ConnectivityState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emit(_i22.ConnectivityState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i22.ConnectivityState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DisplayCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisplayCubit extends _i1.Mock implements _i23.DisplayCubit {
  MockDisplayCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.DisplayState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeDisplayState_6(this, Invocation.getter(#state)),
          )
          as _i8.DisplayState);

  @override
  _i12.Stream<_i8.DisplayState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i8.DisplayState>.empty(),
          )
          as _i12.Stream<_i8.DisplayState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> resizeDisplay({required _i24.Size? viewSize}) =>
      (super.noSuchMethod(
            Invocation.method(#resizeDisplay, [], {#viewSize: viewSize}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> onWindowSizeChanged(_i24.Size? updatedSize) =>
      (super.noSuchMethod(
            Invocation.method(#onWindowSizeChanged, [updatedSize]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> onDisplayTypeSelectionFinished({
    required bool? isPrimaryDisplay,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onDisplayTypeSelectionFinished, [], {
              #isPrimaryDisplay: isPrimaryDisplay,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emit(_i8.DisplayState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i8.DisplayState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OTAUpdateCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOTAUpdateCubit extends _i1.Mock implements _i25.OTAUpdateCubit {
  MockOTAUpdateCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.OTAUpdateState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOTAUpdateState_7(this, Invocation.getter(#state)),
          )
          as _i9.OTAUpdateState);

  @override
  _i12.Stream<_i9.OTAUpdateState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i9.OTAUpdateState>.empty(),
          )
          as _i12.Stream<_i9.OTAUpdateState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> checkForUpdates() =>
      (super.noSuchMethod(
            Invocation.method(#checkForUpdates, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void launchUpdater() => super.noSuchMethod(
    Invocation.method(#launchUpdater, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.OTAUpdateState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i9.OTAUpdateState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TouchscreenCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTouchscreenCubit extends _i1.Mock implements _i26.TouchscreenCubit {
  MockTouchscreenCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i27.VirtualTouchscreenSlotState> get slotsState =>
      (super.noSuchMethod(
            Invocation.getter(#slotsState),
            returnValue: <_i27.VirtualTouchscreenSlotState>[],
          )
          as List<_i27.VirtualTouchscreenSlotState>);

  @override
  bool get state =>
      (super.noSuchMethod(Invocation.getter(#state), returnValue: false)
          as bool);

  @override
  _i12.Stream<bool> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<bool>.empty(),
          )
          as _i12.Stream<bool>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void handlePointerDownEvent(
    _i28.PointerDownEvent? event,
    _i28.BoxConstraints? constraints,
    _i24.Size? touchscreenSize,
  ) => super.noSuchMethod(
    Invocation.method(#handlePointerDownEvent, [
      event,
      constraints,
      touchscreenSize,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePointerMoveEvent(
    _i28.PointerMoveEvent? event,
    _i28.BoxConstraints? constraints,
    _i24.Size? touchscreenSize,
  ) => super.noSuchMethod(
    Invocation.method(#handlePointerMoveEvent, [
      event,
      constraints,
      touchscreenSize,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void handlePointerUpEvent(
    _i28.PointerEvent? event,
    _i28.BoxConstraints? constraints,
  ) => super.noSuchMethod(
    Invocation.method(#handlePointerUpEvent, [event, constraints]),
    returnValueForMissingStub: null,
  );

  @override
  void resetTouchScreen() => super.noSuchMethod(
    Invocation.method(#resetTouchScreen, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendCommands({
    required List<_i29.VirtualTouchScreenCommand>? commands,
  }) => super.noSuchMethod(
    Invocation.method(#sendCommands, [], {#commands: commands}),
    returnValueForMissingStub: null,
  );

  @override
  void sendCommand(_i29.VirtualTouchScreenCommand? command) =>
      super.noSuchMethod(
        Invocation.method(#sendCommand, [command]),
        returnValueForMissingStub: null,
      );

  @override
  void emit(bool? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<bool>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void log(String? message) => super.noSuchMethod(
    Invocation.method(#log, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logException({dynamic exception, StackTrace? stackTrace}) =>
      super.noSuchMethod(
        Invocation.method(#logException, [], {
          #exception: exception,
          #stackTrace: stackTrace,
        }),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i30.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setupAudioConfig(String? configJson) => super.noSuchMethod(
    Invocation.method(#setupAudioConfig, [configJson]),
    returnValueForMissingStub: null,
  );

  @override
  void startAudioFromGesture() => super.noSuchMethod(
    Invocation.method(#startAudioFromGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAudio() => super.noSuchMethod(
    Invocation.method(#stopAudio, []),
    returnValueForMissingStub: null,
  );

  @override
  String getAudioState() =>
      (super.noSuchMethod(
            Invocation.method(#getAudioState, []),
            returnValue: _i31.dummyValue<String>(
              this,
              Invocation.method(#getAudioState, []),
            ),
          )
          as String);

  @override
  _i24.VoidCallback addAudioStateListener(void Function(String)? onState) =>
      (super.noSuchMethod(
            Invocation.method(#addAudioStateListener, [onState]),
            returnValue: () {},
          )
          as _i24.VoidCallback);
}

/// A class which mocks [ReleaseNotesCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockReleaseNotesCubit extends _i1.Mock implements _i32.ReleaseNotesCubit {
  MockReleaseNotesCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ReleaseNotesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeReleaseNotesState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i10.ReleaseNotesState);

  @override
  _i12.Stream<_i10.ReleaseNotesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i10.ReleaseNotesState>.empty(),
          )
          as _i12.Stream<_i10.ReleaseNotesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadReleaseNotes() => super.noSuchMethod(
    Invocation.method(#loadReleaseNotes, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelection({
    required _i33.Version? version,
    required _i34.ChangelogItem? changelogItem,
  }) => super.noSuchMethod(
    Invocation.method(#updateSelection, [], {
      #version: version,
      #changelogItem: changelogItem,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i10.ReleaseNotesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i14.Change<_i10.ReleaseNotesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}
